### ISSUE TITLE
setting up license on linux

### ISSUE THREAD

**Issue by wsnoble** [smith-chem-wisc/FlashLFQ#113]
I am trying to get flashlfq to work on some sample files , but I am getting error message about the LicenceAgreements.toml file.  This file does not exist in our installation. Can you tell me how it is supposed to get created?

```
$ flashlfq --idt "/net/noble/vol1/home/noble/proj/2010_wnoble_crux-tinkering/results/2022-06-21flashlfq-sample/from-michael/AllPeptides_1.psmtsv" --rep "/net/noble/vol1/home/noble/proj/2010_wnoble_crux-tinkering/results/2022-06-21flashlfq-sample/from-michael/" --ppm 5 --chg
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/net/gs/vol3/software/modules-sw/flashlfq/1.2.2/Linux/CentOS7/x86_64/LicenceAgreements.toml' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at Nett.Toml.WriteFileInternal(TomlTable table, String filePath, TomlSettings settings)
   at Nett.Toml.WriteFile[T](T obj, String filePath, TomlSettings settings)
   at Nett.Toml.WriteFile[T](T obj, String filePath)
   at Util.LicenceAgreementSettings.ReadLicenceSettings() in C:\projects\flashlfq\Util\LicenceAgreementSettings.cs:line 43
   at CMD.FlashLfqExecutable.Run(FlashLfqSettings settings) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 96
   at CMD.FlashLfqExecutable.<>c.<Main>b__1_1(FlashLfqSettings options) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 23
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CMD.FlashLfqExecutable.Main(String[] args) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 22
/net/gs/vol3/software/modules-sw/flashlfq/1.2.2/Linux/CentOS7/x86_64/flashlfq: line 4: 26248 Aborted                 (core dumped) ${INSTALL}/dotnet ${INSTALL}/CMD.dll "$@"
```

**Comment by trishorts** [comment]
[LicenceAgreements.zip](https://github.com/smith-chem-wisc/FlashLFQ/files/8952071/LicenceAgreements.zip)
please try unzipping this file in placing it in the directory that contain the executable program

I
