### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by cksakura** [smith-chem-wisc/FlashLFQ#39]
Hello,

My name is Kai and I used FlashLFQ for several weeks. Recently I encountered a problem when using the latest version of FlashLFQ (0.1.101). 

FlashLFQExecutable.exe --idt "D:\Data\test.tsv" --rep "D:\Data\raw" --mbr true
Opening PSM file D:\Data\test.tsv
Done reading PSMs
Setup is OK - running FlashLFQ engine
Assigning MS1 peaks to bins
Quantifying peptides for Run1_C1_2000ng

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at FlashLFQ.FlashLFQEngine.FilterPeaksByIsotopicDistribution(IEnumerable`1 peaks, Identification identification, Int32 chargeState, Boolean lookForBadIsotope, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.<>c__DisplayClass31_0.<QuantifyMS2IdentifiedPeptides>b__4(Tuple`2 range, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`2 body)
   at FlashLFQ.FlashLFQEngine.QuantifyMS2IdentifiedPeptides(RawFileInfo fileInfo, Dictionary`2 mzBins, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.Run()
   at FlashLFQExecutable.FlashLFQExecutable.Main(String[] args) in C:\Users\rmillikin\Source\Repos\FlashLFQ_Master\FlashLFQ Executable\FlashLFQExecutable.cs:line 98

I generated the tsv file by myself so I supposed that there were some problems within it. Does anyone know the reason of this exception?

Thank you for your time.

Kai

**Comment by rmillikin** [comment]
Hello Kai,

It looks like your tsv file is OK. The error message is related to reading the spectrum files. Is it possible for you to upload and share your tsv and spectra files for me to debug? You can email me at rmillikin@wisc.edu for a link to a place to share the files.

The results from 0.1.101 should be the same as version 0.1.100. There was just a large code restructuring to make future development of FlashLFQ easier. You can keep using 0.1.100 for now until this crash is fixed.

Rob

**Comment by rmillikin** [comment]
The issue is indeed with the TSV file - there are identifications with the same peptide BaseSequence/ModSequence, but the identifications have different masses. Apparently this is because the search program does not include the modification in the "Modified Peptides" column. If the Modified Sequence and Base Sequence fields are the same for multiple identifications, but the IDs have different masses, incorrect quantification will occur (a crash or incorrect intensity value).

Example:
PEPTIDE (mass 1000.0)
PEPTIDE (mass 1042.0)

**Comment by trishorts** [comment]
Could conflicts like this be written in an error report.txt file rather than all out crash? Many peptides could be correctly quantified. Is it really necessary to trash the whole run?
