### ISSUE TITLE
Issue Running with .mzML file

### ISSUE THREAD

**Issue by danielgeiszler** [smith-chem-wisc/FlashLFQ#46]
Hello,

I'm having a problem trying to run FlashLFQ. Here is my command line execution and error message:

& '..\FlashLFQ\FlashLFQ\FlashLFQExecutable' --idt flashLFQinput.psmtsv --raw FileName.mzML --rep . --chg false

Opening PSM file flashLFQinput.psmtsv
Done reading PSMs
Setup is OK; read in 12894 identifications; starting FlashLFQ engine
Assigning MS1 peaks to bins
Quantifying peptides for FileName
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at FlashLFQ.FlashLFQEngine.FilterPeaksByIsotopicDistribution(IEnumerable`1 peaks, Identification identification, Int32 chargeState, Boolean lookForBadIsotope, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.<>c__DisplayClass31_0.<QuantifyMS2IdentifiedPeptides>b__4(Tuple`2 range, ParallelLoopState loopState)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](Partitioner`1 source, ParallelOptions parallelOptions, Action`2 body)
   at FlashLFQ.FlashLFQEngine.QuantifyMS2IdentifiedPeptides(RawFileInfo fileInfo, Dictionary`2 mzBins, Dictionary`2 allMs1Scans)
   at FlashLFQ.FlashLFQEngine.Run()
   at FlashLFQExecutable.FlashLFQExecutable.Main(String[] args) in C:\Users\rmillikin\Source\Repos\FlashLFQ\FlashLFQ Executable\FlashLFQExecutable.cs:line 112

Also, your GitHub page says that this supports a custom filetype with the headers "File Name", "Base Sequence", "Full Sequence", "Peptide Monoisotopic Mass", "Scan Retention Time", "Precursor Charge", and "Protein Accession". When I tried to build an input file with these parameters, it failed saying that it was an Unknown file type. I don't see anywhere in the PsmReader.cs source code where this would be supported either.

Please let me know if you can help me with this issue.

Thanks,
Danny

**Comment by trishorts** [comment]
we'll get on this shortly.

**Comment by rmillikin** [comment]
Sorry about that - the latest version should be able to parse generic PSM input. The readme has been updated slightly too, since some of the parameters have changed recently and the readme was out of date.

The crash is a little more involved. I can take a stab at it and guess that the monoisotopic mass in your PSM file may not be consistent between Modified Sequences. Can you double check that you only have one monoisotopic mass per Mod Sequence?

If it's not that (or if you're not sure), are you able to share your PSM file along with one or more of your mzML files?

You may email them to be at rmillikin@wisc.edu .

**Comment by KaiLiCn** [comment]
I also met this issue. The data I used was from _FlashLFQ-master\Test\SampleFiles_ in the download package.

**Comment by trishorts** [comment]
We'll look at it shortly.

**Comment by rmillikin** [comment]
Hello Kai,

Please make sure your FlashLFQ is the latest version. I'm also not sure if that mzML included in the sample files is up to date. I'll upload a new sample files package here, attached.

[SampleFiles.zip](https://github.com/smith-chem-wisc/FlashLFQ/files/1928626/SampleFiles.zip)

**Comment by cksakura** [comment]
Hello,

Thank you for your advice. Currently, I only use the raw files directly and
it works very well.

Best regards,

Kai
