### ISSUE TITLE
Crash with header / PSM identification issues

### ISSUE THREAD

**Issue by Dmorgen** [smith-chem-wisc/FlashLFQ#78]
Hi Guys,

got the following error:
Data files were processed on a VMware, Inc. VMware Virtual Platform computer using Windows version 6.1.7601.65536 with a 64-Bit processor and 26 cores operating at 2.2GHz and 128GB installed RAM.
.NET Framework Version: 4.7 or laterThermo MSFileReader Fileio DLL		Version: 3.0
Thermo MSFileReader Fregistry DLL		Version: 3.0
Thermo MSFileReader Rawfile Com Interface		Version: 3.0.31.0

e: System.Exception: Could not interpret PSM header labels from file: D:\fass\Qsox1 ox. FlashLFQ data.txt
   at CMD.PsmReader.ReadPsms(String filepath, Boolean silent, List`1 rawfiles)
   at GUI.MainWindow.RunFlashLfq() in C:\Users\rmillikin\Source\Repos\FlashLFQ_Master\GUI\MainWindow.xaml.cs:line 305e.Message: Could not interpret PSM header labels from file: D:\fass\Qsox1 ox. FlashLFQ data.txte.InnerException: e.Source: CMDe.StackTrace:    at CMD.PsmReader.ReadPsms(String filepath, Boolean silent, List`1 rawfiles)
   at GUI.MainWindow.RunFlashLfq() in C:\Users\rmillikin\Source\Repos\FlashLFQ_Master\GUI\MainWindow.xaml.cs:line 305e.TargetSite: System.Collections.Generic.List`1[FlashLFQ.Identification] ReadPsms(System.String, Boolean, System.Collections.Generic.List`1[FlashLFQ.SpectraFileInfo])

attached is the ID file
[Qsox1 ox. FlashLFQ data.txt](https://github.com/smith-chem-wisc/FlashLFQ/files/3206045/Qsox1.ox.FlashLFQ.data.txt)

thanks!
D.

**Comment by trishorts** [comment]
Hi D. I'm sure Rob will look at this as soon as he gets in. Are you going to ASMS? Let us know is you have posters/presentations so we can stop by.

**Comment by rmillikin** [comment]
Hi David,

The headers in the ID file are case-sensitive. The "peptide monoisotopic mass" label must instead be "Peptide Monoisotopic Mass".

Hope to see you at ASMS!

**Comment by Dmorgen** [comment]
Sorry about that – I’ve missed it…
I won’t be coming to ASMS this year. I’m going to HUPO instead.
However, I should visit the Coon lab soon, so I might drop by…

Thanks!
