### ISSUE TITLE
Fail in the command-line mode

### ISSUE THREAD

**Issue by cksakura** [smith-chem-wisc/FlashLFQ#97]
Hello,

When I was using the label-free quantification by the CMD.exe, I found a little problem. If the spectra file repository contains more raw files than that are in the "ExperimentalDesign.tsv" file, which means I only using part of the raw files in this folder for the quantification, an Exception will be throw. 

> Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'fileName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at CMD.FlashLfqExecutable.Run(FlashLfqSettings settings) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 267
   at CMD.FlashLfqExecutable.<>c.<Main>b__1_1(FlashLfqSettings options) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 23
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CMD.FlashLfqExecutable.Main(String[] args) in C:\projects\flashlfq\CMD\FlashLFQExecutable.cs:line 22

I'm not sure if the reason for the problem is the raw files in the folder and in the "ExperimentalDesign.tsv" file are not exactly matched.

Thank you.

**Comment by trishorts** [comment]
i don't think that it matters if there are extra files.

Can you tell me, did you calibrate the raw files before you did the search? If so, the calibration creates a new raw name and this name is what is needed in the experimental design to match with the output.

Basically, the filenames in the AllPSMs.psmtsv first column, should match the filenames in the first column of the experimental design.

If this is not the problem, I think Rob will look at this in the morning.

**Comment by cksakura** [comment]
Hello,

Thank you for your quick response. I didn't use any calibrate and the file name in the identification file and the "ExperimentalDesign.tsv" are matched. I supposed the reason for the problem because in the error information 

> Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'fileName' was not present in the dictionary.

the "fileName" is a file in the raw file folder but was not searched this time so not exist in the identification file or "ExperimentalDesign.tsv".
Actually, I use GUI.exe first and it runs well. I just added the raw files used in this search but not all the raw files in the folder. The  "ExperimentalDesign.tsv" generated automatically. Then I ended the GUI task and switched to CMD.exe. Because the "ExperimentalDesign.tsv" file was found in the raw files folder it will use it, then throw the problem.

Thank you for your time. I'm not in any rush.
